language: objective-c
xcode_sdk: iphonesimulator11.1
osx_image: xcode9.1
xcode_sdk: iphonesimulator
install: true
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - set -o pipefail && xcodebuild -project DataKernel.xcodeproj -scheme DataKernel-iOS -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && xcodebuild test -project DataKernel.xcodeproj -scheme DataKernel -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' ONLY_ACTIVE_ARCH=NO | xcpretty
